### ISSUE TITLE
add prettier plugin for importOrder config

### ISSUE THREAD

**Issue by devMozao** [devMozao/eruption#9]
case: https://github.com/trivago/prettier-plugin-sort-imports

**Comment by Joabesv** [comment]
can i take this one?

**Comment by devMozao** [comment]
> can i take this one?

of course! in `.prettierrc` config file you'll see the importOrder config that was improvised there.

**Comment by Joabesv** [comment]
#11 Done, didn't change your regExp :) just added the other configs recommended in the plugin readme

**Comment by devMozao** [comment]
done at https://github.com/devMozao/eruption/pull/11 by @Joabesv
